export const SITE_NAME = 'JayarathnaTech Solutions'
// Must match Vercel's primary domain exactly — the apex domain 308-redirects
// here, so pointing this at the apex instead would make every sitemap/canonical
// URL a redirect target and Search Console would flag pages as unindexable.
export const SITE_URL = 'https://www.jayarathnatechsolutions.com'

// Default social-share preview image (1200×630) — generated by
// scripts/generate-og-image.mjs. Pages can override with a more specific
// image (e.g. a project's cover image) via the Seo component's `image` prop.
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.jpg`

export const siteContact = {
    email: 'info@jayarathnatechsolutions.com',
    phone: '+94 78 628 7211',
    location: 'Negombo, Sri Lanka',
}

// Registered business details used on formal documents (quotes, invoices,
// agreements) — matches the company letterhead.
export const siteLetterhead = {
    registeredName: 'JayarathnaTech Solutions (Pvt) Ltd',
    regNo: 'PV00223764',
    address: 'No. 90/28/4, Gurugewaththa, Seeduwa Road, Kotugoda, Sri Lanka',
    phone: '+94 75 282 8091',
    phoneAlt: siteContact.phone,
    website: 'www.jayarathnatechsolutions.com',
    email: 'info@jayarathnatechsolutions.com',
}

export const siteSocial = {
    github: 'https://github.com/JayarathnaTech-Solutions',
    facebook: 'https://web.facebook.com/JayarathnaTechSolutions/',
    linkedin: 'https://www.linkedin.com/company/jayarathnatech-solutions',
    instagram: 'https://www.instagram.com/jayarathnatech_solutions/',
}

const TITLE_TAG_MAX = 60

// Google truncates title tags around ~60 characters. Blog post headlines are
// already written as full, keyword-rich SEO titles on their own, so only
// append the brand suffix when there's room — otherwise the suffix pushes
// the whole tag past the truncation point and buries the actual keywords.
export function buildPageTitle(rawTitle: string) {
    const withBrand = `${rawTitle} — ${SITE_NAME}`
    return withBrand.length <= TITLE_TAG_MAX ? withBrand : rawTitle
}

export const navLinks = [
    { to: '/', label: 'Home', end: true },
    { to: '/about', label: 'About' },
    { to: '/services', label: 'Services' },
    { to: '/projects', label: 'Projects' },
    { to: '/blog', label: 'Blog' },
    { to: '/contact', label: 'Contact' },
]

// Base Organization structured data (schema.org), shared by the sitewide
// JSON-LD in PublicLayout and extended with aggregateRating/review on Home.
//
// Typed as both Organization and LocalBusiness so the entry qualifies for
// Google's local pack (Sri Lanka searches) as well as general knowledge-panel
// treatment. Fields here must match what's visibly shown on the site (Google
// flags structured data that doesn't match page content) — that's why there's
// no street address or geo coordinates: the public site only ever shows
// "Negombo, Sri Lanka", not the full registered address from siteLetterhead.
export function buildOrganizationSchema() {
    return {
        '@context': 'https://schema.org',
        '@type': ['Organization', 'LocalBusiness'],
        '@id': `${SITE_URL}/#organization`,
        name: SITE_NAME,
        url: SITE_URL,
        logo: `${SITE_URL}/favicon.svg`,
        image: DEFAULT_OG_IMAGE,
        email: siteContact.email,
        telephone: siteContact.phone,
        priceRange: '$$',
        address: {
            '@type': 'PostalAddress',
            addressLocality: 'Negombo',
            addressRegion: 'Western Province',
            addressCountry: 'LK',
        },
        openingHoursSpecification: {
            '@type': 'OpeningHoursSpecification',
            dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
            opens: '09:00',
            closes: '18:00',
        },
        areaServed: ['Sri Lanka', 'Worldwide'],
        sameAs: [siteSocial.github, siteSocial.facebook, siteSocial.linkedin, siteSocial.instagram],
        description:
            'JayarathnaTech Solutions is a software company based in Negombo, Sri Lanka, building web applications, e-commerce platforms, and custom software for clients in Sri Lanka and internationally.',
    }
}

// BreadcrumbList structured data — reflects the page's position in the site
// hierarchy for rich-result breadcrumbs. `items` should run from the home
// page to the current page, e.g. [{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }].
export function buildBreadcrumbSchema(items: { name: string; url: string }[]) {
    return {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: items.map((item, index) => ({
            '@type': 'ListItem',
            position: index + 1,
            name: item.name,
            item: `${SITE_URL}${item.url}`,
        })),
    }
}

// BlogPosting structured data for an individual blog post — rich-result
// eligible article markup, linked back to the sitewide Organization entity.
export function buildBlogPostingSchema(post: { slug: string; title: string; description: string; publishedAt: string; tags: string[] }) {
    return {
        '@context': 'https://schema.org',
        '@type': 'BlogPosting',
        headline: post.title,
        description: post.description,
        url: `${SITE_URL}/blog/${post.slug}`,
        mainEntityOfPage: `${SITE_URL}/blog/${post.slug}`,
        datePublished: post.publishedAt,
        keywords: post.tags.join(', '),
        articleSection: post.tags[0],
        inLanguage: 'en',
        image: DEFAULT_OG_IMAGE,
        author: { '@id': `${SITE_URL}/#organization` },
        publisher: { '@id': `${SITE_URL}/#organization` },
    }
}
