// Every shared interface and type, grouped one file per domain (see
// .ai/rules/typescript.md). Import from this barrel: `from '../types'`.
export type * from './staff'
export type * from './project'
export type * from './company'
export type * from './testimonial'
export type * from './currency'
export type * from './quote'
export type * from './blog'
export type * from './contact'
export type * from './settings'
export type * from './customer'
export type * from './engagement'
export type * from './invoice'
export type * from './chat'
